name: ex7make

on:
  push:
    branches: [ "main" ]
    paths: "ex7/*.cpp"

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: execute
      run: ./ex7
